### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by jerbob92**
- Fixed the kernel revision (this is now the latest revision in the 4.16 branch, the used revision does not exist (anymore) in the selected branch), we can also go to 4.17, but it requires minor changes in the kernel and rtl8189es bb
 - Updated kernel defconfig for orange-pi-pc-plus (copied from https://github.com/megous/linux/blob/orange-pi-4.16/linux-4.16-32)
 - Updated meta-openembedded, meta-qt and poky to latest revision in the rocko branch
 - Fixed the systemd append to add space to prevent a wrong packeconfig

Also, I could't get it to build with mender due to a u-boot issue, could you maybe check?
https://github.com/mendersoftware/meta-mender/pull/465#issuecomment-397877332

```
ERROR: u-boot-fw-utils-mender-auto-provided-1.0-r0 do_package: objcopy failed with exit code 1 (cmd was 'arm-oe-linux-gnueabi-objcopy' --only-keep-debug '/home/poky/orange-pi-distro/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/fw_setenv' '/home/poky/orange-pi-distro/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/.debug/fw_setenv'):
arm-oe-linux-gnueabi-objcopy:/home/poky/orange-pi-distro/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/package/sbin/fw_setenv: File format not recognized
ERROR: u-boot-fw-utils-mender-auto-provided-1.0-r0 do_package: Function failed: split_and_strip_files
ERROR: Logfile of failure stored in: /home/poky/orange-pi-distro/build/tmp-glibc/work/cortexa7hf-neon-vfpv4-oe-linux-gnueabi/u-boot-fw-utils-mender-auto-provided/1.0-r0/temp/log.do_package.11989
ERROR: Task (/home/poky/orange-pi-distro/meta-mender/meta-mender-core/recipes-bsp/u-boot/u-boot-fw-utils-mender-auto-provided_1.0.bb:do_package) failed with exit code '1'
```

### CODE REVIEW

**Comment by Halolo** [comment]
Sorry I didn't saw your PR and just pushed my work of the weekend, I switched the kernel to mainline 4.17, now that the HDMI support is merged. Also the yocto version has been updated to "sumo".

I didn't try to build for pc-plus, I'll check later this week if something is broken, like the wifi driver as you mentioned.

**Comment by jerbob92** [comment]
Hi, no problem! 4.17 is even better :) But what about the systemd bb changes (to prevent `systemd-1_237-r0 do_configure: QA Issue: systemd: invalid PACKAGECONFIG: resolvednetworkd [invalid-packageconfig]` and defconfig update?
Also, shouldn't you use `git://github.com/megous/linux.git;protocol=git;branch=orange-pi-4.17` instead of `git://github.com/torvalds/linux.git;protocol=git;branch=master`, it seems to contain more fixes than just the HDMI:
```
CPU frequency and voltage scaling (cpufreq)
Thermal regulation (if CPU heats above certain temperature, it will try to cool itself down by reducing CPU frequency)
HDMI audio support (from Jernej Skrabec)
Configure on-board micro-switches to perform system power off function
Wireguard (https://www.wireguard.com/)
```
Or are all these things merged? Plus the provided patches do not apply to the torvalds repo.
The wifi driver just requires a newer revision to build.

**Comment by Halolo** [comment]
cpufreq for H3 is scheduled for 4.18, but I think you're right, I'll probably bring back the previous kernel. I used the mainline to investigate the mali egl acceleration problem I have via qt or X11, as it's a good reference to debbug on, but I should have done that in a branch.

To answer your comments on the files yes, I will add the "mali related" kernel modifications to pc plus, and include your fixes related to systemd and get the new kernel config base for 4.17.

Concerning the patch to add the Mali node to the dts it does apply for me, maybe you tested it out of a yocto environment? The lines may have changed and generates a warning in yocto. Anyway I will apply the mali400 node in the H3 specific dtsi because H5 has a mali 450, so that was not the good file to add the node in.

**Comment by jerbob92** [comment]
Sounds good. Indeed tested out of a yocto environment. 
And If the H3 requires a different patch from H5, maybe split up the kernel bb?

Also be warned that you can't just copy over the newly generated defconfig, it contains this:
```
CONFIG_EXTRA_FIRMWARE="regulatory.db regulatory.db.p7s brcm/brcmfmac43362-sdio.bin brcm/brcmfmac43362-sdio.txt brcm/bcm20710a1.hcd"
CONFIG_EXTRA_FIRMWARE_DIR="/workspace/megous.com/orangepi-pc/firmware"
```
And these files aren't provided, I'm also not sure what they are for, sounds like wifi driver. Also replacing these lines with:
```
CONFIG_EXTRA_FIRMWARE=""
```
As it is in the current defconfig, you will still have other compile errors in rtl8189es and mali.

**Comment by jerbob92** [comment]
Maintainer of that kernel tree confirmed that these firmware lines are not needed.
I looked a bit at the differences between the current defconfig and https://github.com/megous/linux/blob/orange-pi-4.14/linux-4.14-32, I copied some over (like CONFIG_MODULES=y, CONFIG_CMDLINE=" loglevel=3" and CONFIG_CMDLINE_FROM_BOOTLOADER=y), now the kernel compiling works.

**Comment by jerbob92** [comment]
@Halolo Another note: shouldn't the patch `0001-sunxi-h3-Fix-PLL1-setup-to-never-use-dividers.patch` be applied to u-boot-opi? According to readme of https://github.com/megous/linux

**Pull request closed without merging**
